//pipeline{
  //  agent{
    //    label "nodejs"
    //}
    //stages{
      //  stage("Install dependencies"){
        //    steps{
          //      sh "npm ci"
            //}
        //}

        //stage("Check Style"){
          //  steps{
            //    sh "npm run lint"
            //}
        //}

       // stage("Test"){
         //   steps{
         //       sh "npm test"
          //  }
       // }

        // Add the "Deploy" stage here
  //  }
//}
pipeline{

agent any

stages{

stage('Deploy') {

steps {

sh '''

oc project yqaphi-deploy-strategies

oc start-build greeting-service --follow --wait

'''

}

}

}

}
